version: '3.3'

services:
  
  kaldi:
    build: kaldi
  
  model:
    build: model
    volumes:
      - ./model:/model
  
  web:
    build: web
    volumes:
      - ./web:/server
    ports:
      - 8080:8080