version: '3.3'
services:

  node:
    build: asr-web
    volumes:
      - ./asr-web/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    tty: true
    links: 
      - web

  model:
    build: model
    volumes:
      - ./model/model:/model

  web:
    build: web
    volumes:
      - ./web:/server
    ports: 
      - 8080:8080