version: '3.3'

services:
  
  kaldi:
    build: kaldi
  
  model:
    build: model
    ports:
      - 5050:5050

  web:
    build: web
    ports:
      - 8080:8080
    environment:
      - PYTHONUNBUFFERED=1
    